"""Generate a draft YAML contract from an introspected schema.

This turns the live database into a starting-point contract so teams don't have
to hand-write the YAML. The output is a *draft*: it captures the current reality
and is meant to be reviewed and trimmed to the invariants that actually matter.
"""

from __future__ import annotations

from typing import Any

import yaml

from datagate.models import Schema

# Numeric types for which precision/scale are meaningful (information_schema also
# reports a precision for integers, which we must not emit).
_NUMERIC_TYPES = {"numeric", "decimal"}


def contract_from_schema(schema: Schema, database: str) -> dict[str, Any]:
    """Build a contract mapping mirroring ``schema``."""
    structure: list[dict[str, Any]] = []
    for table in schema.tables:
        entry: dict[str, Any] = {"table": table.name}

        columns = [_column_entry(column) for column in table.columns]
        if columns:
            entry["columns"] = columns
        if table.primary_key:
            entry["primary_key"] = list(table.primary_key)
        if table.foreign_keys:
            entry["foreign_keys"] = [
                {
                    "columns": list(fk.columns),
                    "references_table": fk.referenced_table,
                    "references_columns": list(fk.referenced_columns),
                }
                for fk in table.foreign_keys
            ]
        indexes = [
            {
                "name": index.name,
                "columns": list(index.columns),
                "unique": index.is_unique,
            }
            for index in table.indexes
            if not index.is_primary  # PK index is already covered by primary_key
        ]
        if indexes:
            entry["indexes"] = indexes

        structure.append(entry)

    return {
        "version": 1,
        "database": database,
        "schema": schema.name,
        "structure": structure,
        "audit": [],
    }


def _column_entry(column) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "name": column.name,
        "type": column.data_type,
        "nullable": column.is_nullable,
    }
    if column.char_max_length is not None:
        entry["max_length"] = column.char_max_length
    if column.data_type in _NUMERIC_TYPES and column.numeric_precision is not None:
        entry["precision"] = column.numeric_precision
        if column.numeric_scale is not None:
            entry["scale"] = column.numeric_scale
    return entry


def dump_contract(mapping: dict[str, Any]) -> str:
    """Serialise a contract mapping to YAML, preserving key order."""
    header = (
        "# Draft contract generated by `datagate generate`.\n"
        "# Review it: keep the invariants that matter, drop the incidental ones.\n"
    )
    body = yaml.safe_dump(
        mapping, sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    return header + body
